## CardDatabase (Autoload)
## Loads all game data from JSON files generated by the YAML-to-JSON converter.
## Access via: CardDatabase.get_card("neural_network")
extends Node

# ── Data Stores ──────────────────────────────────────────────────────────────

## card_id -> CardData resource
var cards: Dictionary = {}
## keyword_id -> KeywordDef
var keywords: Dictionary = {}
## status_id -> StatusDef  
var statuses: Dictionary = {}
## category_id -> CategoryDef
var categories: Dictionary = {}
## faction_id -> FactionDef
var factions: Dictionary = {}
## Game rules constants
var rules: Dictionary = {}

# ── Data Paths ───────────────────────────────────────────────────────────────

const DATA_DIR := "res://data/"

# ── Lifecycle ────────────────────────────────────────────────────────────────

func _ready() -> void:
	_load_all_data()
	print("[CardDatabase] Loaded %d cards, %d keywords, %d statuses, %d factions" % [
		cards.size(), keywords.size(), statuses.size(), factions.size()
	])


func _load_all_data() -> void:
	rules = _load_json("rules.json")
	_load_keywords()
	_load_statuses()
	_load_categories()
	_load_factions()
	_load_cards()


# ── Public API ───────────────────────────────────────────────────────────────

## Get a CardData by its ID. Returns null if not found.
func get_card(card_id: String) -> CardData:
	return cards.get(card_id)


## Get all cards of a specific type (Unit, Spell, Artifact, Hero).
func get_cards_by_type(card_type: String) -> Array[CardData]:
	var result: Array[CardData] = []
	for card in cards.values():
		if card.type == card_type:
			result.append(card)
	return result


## Get all cards belonging to a faction.
func get_cards_by_faction(faction_name: String) -> Array[CardData]:
	var result: Array[CardData] = []
	for card in cards.values():
		if faction_name in card.factions:
			result.append(card)
	return result


## Get all neutral cards (for the shared draw pile).
func get_neutral_cards() -> Array[CardData]:
	return get_cards_by_faction("Neutral")


## Get the hero card for a faction.
func get_hero(faction_name: String) -> CardData:
	for card in cards.values():
		if card.type == "Hero" and faction_name in card.factions:
			return card
	return null


## Get all available factions (those with a hero and enough cards).
func get_playable_factions() -> Array[String]:
	var result: Array[String] = []
	for faction_id in factions:
		var f = factions[faction_id]
		if f.get("hero") != null:
			result.append(f["name"])
	return result


## Search cards by name (partial match, case-insensitive).
func search_cards(query: String) -> Array[CardData]:
	var result: Array[CardData] = []
	var q: String = query.to_lower()
	for card in cards.values():
		if q in card.name.to_lower():
			result.append(card)
	return result


# ── Loaders ──────────────────────────────────────────────────────────────────

func _load_json(filename: String) -> Dictionary:
	var path: String = DATA_DIR + filename
	if not FileAccess.file_exists(path):
		push_error("[CardDatabase] File not found: %s" % path)
		return {}
	var file := FileAccess.open(path, FileAccess.READ)
	var json_text: String = file.get_as_text()
	file.close()
	var json := JSON.new()
	var err: int = json.parse(json_text)
	if err != OK:
		push_error("[CardDatabase] JSON parse error in %s: %s" % [path, json.get_error_message()])
		return {}
	return json.data if json.data is Dictionary else {}


func _load_json_array(filename: String) -> Array:
	var path: String = DATA_DIR + filename
	if not FileAccess.file_exists(path):
		push_error("[CardDatabase] File not found: %s" % path)
		return []
	var file := FileAccess.open(path, FileAccess.READ)
	var json_text: String = file.get_as_text()
	file.close()
	var json := JSON.new()
	var err: int = json.parse(json_text)
	if err != OK:
		push_error("[CardDatabase] JSON parse error in %s: %s" % [path, json.get_error_message()])
		return []
	return json.data if json.data is Array else []


func _load_cards() -> void:
	var card_array: Array = _load_json_array("cards.json")
	for entry in card_array:
		var card := CardData.new()
		card.id = entry.get("id", "")
		card.name = entry.get("name", "")
		card.type = entry.get("type", "Unknown")
		card.rarity = entry.get("rarity", "Unknown")
		card.factions = Array(entry.get("factions", []))
		card.categories = Array(entry.get("categories", []))
		card.base_power = entry.get("power", 0) if entry.get("power") != null else 0
		card.has_ability = entry.get("has_ability", false)
		card.ability_text = entry.get("ability_text", "")
		card.artwork_path = entry.get("artwork", "")
		
		# Parse structured effects
		var effects_data = entry.get("effects", [])
		for eff in effects_data:
			var effect := CardEffect.new()
			effect.type = eff.get("type", "complex")
			effect.trigger = eff.get("trigger", "passive")
			effect.value = eff.get("value", 0)
			effect.status = eff.get("status", "")
			effect.stacks = eff.get("stacks", 0)
			effect.timer_value = eff.get("timer_value", 0)
			effect.upkeep_cost = eff.get("upkeep_cost", 0)
			effect.tribute_cost = eff.get("tribute_cost", 0)
			effect.hoard_threshold = eff.get("hoard_threshold", 0)
			effect.charges = eff.get("charges", 0)
			effect.raw_text = eff.get("raw_text", "")
			card.effects.append(effect)
		
		cards[card.id] = card


func _load_keywords() -> void:
	var kw_array: Array = _load_json_array("keywords.json")
	for entry in kw_array:
		keywords[entry.get("id", "")] = entry


func _load_statuses() -> void:
	var st_array: Array = _load_json_array("statuses.json")
	for entry in st_array:
		statuses[entry.get("id", "")] = entry


func _load_categories() -> void:
	var cat_array: Array = _load_json_array("categories.json")
	for entry in cat_array:
		categories[entry.get("id", "")] = entry


func _load_factions() -> void:
	var fac_array: Array = _load_json_array("factions.json")
	for entry in fac_array:
		factions[entry.get("id", "")] = entry
