## CardDatabase (Autoload)
## Loads all game data from JSON files generated by the YAML-to-JSON converter.
## Access via: CardDatabase.get_card("neural_network")
extends Node

# ── Data Stores ──────────────────────────────────────────────────────────────

## card_id -> CardData resource
var cards: Dictionary = {}
## keyword_id -> KeywordDef
var keywords: Dictionary = {}
## status_id -> StatusDef  
var statuses: Dictionary = {}
## category_id -> CategoryDef
var categories: Dictionary = {}
## faction_id -> FactionDef
var factions: Dictionary = {}
## Game rules constants
var rules: Dictionary = {}

# ── Data Paths ───────────────────────────────────────────────────────────────

const DATA_DIR := "res://data/"

# ── Lifecycle ────────────────────────────────────────────────────────────────

func _ready() -> void:
	_load_all_data()
	print("[CardDatabase] Loaded %d cards, %d keywords, %d statuses, %d factions" % [
		cards.size(), keywords.size(), statuses.size(), factions.size()
	])


func _load_all_data() -> void:
	rules = _load_json("rules.json")
	_load_keywords()
	_load_statuses()
	_load_categories()
	_load_factions()
	_load_cards()


# ── Public API ───────────────────────────────────────────────────────────────

## Get a CardData by its ID. Returns null if not found.
func get_card(card_id: String) -> CardData:
	return cards.get(card_id)


## Resolve ability text: strip Obsidian wiki links, return plain readable string.
## [[Keywords#^deploy|Deploy]] → "Deploy", **bold** → bold BBCode.
func resolve_ability_text(raw: String) -> String:
	var result: String = raw
	# Strip [[...|text]] wiki links → keep display text
	var regex := RegEx.new()
	regex.compile("\\[\\[[^\\]]*\\|([^\\]]+)\\]\\]")
	var match_result := regex.search(result)
	while match_result:
		result = result.replace(match_result.get_string(), match_result.get_string(1))
		match_result = regex.search(result)
	# Strip bare [[text]] links with no pipe
	var regex2 := RegEx.new()
	regex2.compile("\\[\\[([^\\]|]+)\\]\\]")
	match_result = regex2.search(result)
	while match_result:
		result = result.replace(match_result.get_string(), match_result.get_string(1))
		match_result = regex2.search(result)
	# Convert **bold** → [b]bold[/b] for BBCode
	var regex3 := RegEx.new()
	regex3.compile("\\*\\*([^*]+)\\*\\*")
	match_result = regex3.search(result)
	while match_result:
		result = result.replace(match_result.get_string(), "[b]%s[/b]" % match_result.get_string(1))
		match_result = regex3.search(result)
	return result


## Get all cards of a specific type (Unit, Spell, Artifact, Hero).
func get_cards_by_type(card_type: String) -> Array[CardData]:
	var result: Array[CardData] = []
	for card in cards.values():
		if card.type == card_type:
			result.append(card)
	return result


## Get all cards belonging to a faction.
func get_cards_by_faction(faction_name: String) -> Array[CardData]:
	var result: Array[CardData] = []
	for card in cards.values():
		if faction_name in card.factions:
			result.append(card)
	return result


## Get all neutral cards (for the shared draw pile).
func get_neutral_cards() -> Array[CardData]:
	return get_cards_by_faction("Neutral")


## Get the hero card for a faction.
func get_hero(faction_name: String) -> CardData:
	for card in cards.values():
		if card.type == "Hero" and faction_name in card.factions:
			return card
	return null


## Get all available factions (those with a hero and enough cards).
func get_playable_factions() -> Array[String]:
	var result: Array[String] = []
	for faction_id in factions:
		var f = factions[faction_id]
		if f.get("hero") != null:
			result.append(f["name"])
	return result


## Search cards by name (partial match, case-insensitive).
func search_cards(query: String) -> Array[CardData]:
	var result: Array[CardData] = []
	var q: String = query.to_lower()
	for card in cards.values():
		if q in card.name.to_lower():
			result.append(card)
	return result


# ── Loaders ──────────────────────────────────────────────────────────────────

func _load_json(filename: String) -> Dictionary:
	var path: String = DATA_DIR + filename
	if not FileAccess.file_exists(path):
		push_error("[CardDatabase] File not found: %s" % path)
		return {}
	var file := FileAccess.open(path, FileAccess.READ)
	var json_text: String = file.get_as_text()
	file.close()
	var json := JSON.new()
	var err: int = json.parse(json_text)
	if err != OK:
		push_error("[CardDatabase] JSON parse error in %s: %s" % [path, json.get_error_message()])
		return {}
	return json.data if json.data is Dictionary else {}


func _load_json_array(filename: String) -> Array:
	var path: String = DATA_DIR + filename
	if not FileAccess.file_exists(path):
		push_error("[CardDatabase] File not found: %s" % path)
		return []
	var file := FileAccess.open(path, FileAccess.READ)
	var json_text: String = file.get_as_text()
	file.close()
	var json := JSON.new()
	var err: int = json.parse(json_text)
	if err != OK:
		push_error("[CardDatabase] JSON parse error in %s: %s" % [path, json.get_error_message()])
		return []
	return json.data if json.data is Array else []


func _load_cards() -> void:
	var card_array: Array = _load_json_array("cards.json")
	var faction_card_index: Dictionary = _build_faction_card_index()
	for entry in card_array:
		if str(entry.get("id", "")).strip_edges() == "":
			continue
		var card := CardData.new()
		card.id = entry.get("id", "")
		card.name = entry.get("name", "")
		card.type = _normalize_card_type(entry.get("type", "Unknown"), entry)
		card.rarity = _normalize_rarity(entry.get("rarity", "Unknown"), entry)
		card.factions = _normalize_factions(card.id, Array(entry.get("factions", [])), faction_card_index, entry)
		card.categories = Array(entry.get("categories", []))
		card.base_power = entry.get("power", 0) if entry.get("power") != null else 0
		if card.type in ["Unit", "Hero"] and card.base_power <= 0:
			card.base_power = GameConstants.STARTING_HERO_HP if card.type == "Hero" else 1
		card.has_ability = entry.get("has_ability", false)
		card.ability_text = entry.get("ability_text", "")
		card.artwork_path = entry.get("artwork", "")
		
		# Parse structured effects
		var effects_data = entry.get("effects", [])
		for eff in effects_data:
			var effect := CardEffect.new()
			effect.type = eff.get("type", "complex")
			effect.trigger = eff.get("trigger", "passive")
			effect.value = eff.get("value", 0)
			effect.status = eff.get("status", "")
			effect.stacks = eff.get("stacks", 0)
			effect.timer_value = eff.get("timer_value", 0)
			effect.upkeep_cost = eff.get("upkeep_cost", 0)
			effect.tribute_cost = eff.get("tribute_cost", 0)
			effect.hoard_threshold = eff.get("hoard_threshold", 0)
			effect.pay_cost = eff.get("pay_cost", 0)
			effect.initial_charges = eff.get("initial_charges", 0)
			effect.charges = eff.get("charges", 0)
			effect.max_charges = eff.get("max_charges", 0)
			effect.counter_delta = eff.get("counter_delta", 0)
			effect.counter_threshold = eff.get("counter_threshold", 0)
			effect.max_uses_per_turn = eff.get("max_uses_per_turn", 0)
			effect.permanent_status = eff.get("permanent_status", false)
			effect.target_scope = eff.get("target_scope", "enemy")
			effect.target_kind = eff.get("target_kind", "card")
			effect.area = eff.get("area", false)
			effect.requires_target = eff.get("requires_target", true)
			effect.raw_text = eff.get("raw_text", "")
			card.effects.append(effect)

		_ensure_pay_effects_from_text(card)

		if card.ability_text.strip_edges() == "" and card.effects.is_empty():
			card.has_ability = false
		
		cards[card.id] = card


func _ensure_pay_effects_from_text(card: CardData) -> void:
	if card.ability_text.strip_edges() == "":
		return
	if _has_costed_pay_effect(card):
		return
	var pay_regex := RegEx.new()
	pay_regex.compile("(?i)\\bpay\\s+(\\d+)")
	for raw_line in card.ability_text.split("\n"):
		var line := str(raw_line).strip_edges()
		if line == "":
			continue
		var pay_match := pay_regex.search(line)
		if not pay_match:
			continue
		var cost := int(pay_match.get_string(1))
		var added := _append_simple_pay_effects(card, line, cost)
		if not added:
			var effect := _new_pay_effect("complex", cost, line)
			effect.requires_target = false
			card.effects.append(effect)


func _has_costed_pay_effect(card: CardData) -> bool:
	for effect in card.effects:
		if effect.trigger == "pay" and effect.pay_cost > 0:
			return true
	return false


func _append_simple_pay_effects(card: CardData, line: String, cost: int) -> bool:
	var lower := line.to_lower()
	var added := false
	if "destroy self" in lower:
		var effect := _new_pay_effect("destroy", cost, line)
		effect.target_scope = "self"
		effect.requires_target = false
		card.effects.append(effect)
		added = true
	elif "destroy" in lower:
		card.effects.append(_new_pay_effect("destroy", cost, line))
		added = true

	if "banish self" in lower:
		var effect := _new_pay_effect("banish", cost, line)
		effect.target_scope = "self"
		effect.requires_target = false
		card.effects.append(effect)
		added = true
	elif "banish" in lower:
		card.effects.append(_new_pay_effect("banish", cost, line))
		added = true

	var boost_value := _first_number_after(lower, "boost")
	if boost_value > 0:
		var effect := _new_pay_effect("boost", cost, line)
		effect.value = boost_value
		effect.target_scope = "self" if "self" in lower else "ally"
		effect.target_kind = "unit"
		effect.requires_target = not ("self" in lower)
		card.effects.append(effect)
		added = true

	if "heal" in lower:
		var effect := _new_pay_effect("heal", cost, line)
		effect.value = _first_number_after(lower, "heal")
		effect.target_scope = "ally"
		effect.target_kind = "hero" if "hero" in lower else "unit"
		effect.requires_target = not ("your hero" in lower)
		card.effects.append(effect)
		added = true

	var damage_value := _first_damage_value(lower)
	if damage_value > 0:
		var effect := _new_pay_effect("damage", cost, line)
		effect.value = damage_value
		effect.target_scope = "any" if "a hero" in lower or "hero" in lower else "enemy"
		effect.target_kind = "hero" if "hero" in lower else "unit"
		effect.requires_target = true
		card.effects.append(effect)
		added = true

	var draw_value := _first_number_after(lower, "draw")
	if draw_value > 0:
		var effect := _new_pay_effect("draw", cost, line)
		effect.value = draw_value
		effect.target_scope = "self"
		effect.requires_target = false
		card.effects.append(effect)
		added = true

	for status_name in ["invisible", "vulnerable", "cursed", "crit", "poison", "burn", "wither"]:
		if status_name in lower:
			var effect := _new_pay_effect("apply_status", cost, line)
			effect.status = status_name.capitalize()
			effect.stacks = 1
			effect.target_scope = "self" if "self" in lower else "enemy"
			effect.target_kind = "card"
			effect.requires_target = not ("self" in lower)
			card.effects.append(effect)
			added = true
	if added:
		_charge_pay_line_once(card, line, cost)
	return added


func _charge_pay_line_once(card: CardData, raw_text: String, cost: int) -> void:
	var charged := false
	for effect in card.effects:
		if effect.trigger != "pay" or effect.raw_text != raw_text:
			continue
		if charged:
			effect.pay_cost = 0
		else:
			effect.pay_cost = cost
			charged = true


func _new_pay_effect(effect_type: String, cost: int, raw_text: String) -> CardEffect:
	var effect := CardEffect.new()
	effect.type = effect_type
	effect.trigger = "pay"
	effect.pay_cost = cost
	effect.raw_text = raw_text
	effect.target_scope = "enemy"
	effect.target_kind = "card"
	effect.requires_target = true
	return effect


func _first_number_after(text: String, word: String) -> int:
	var regex := RegEx.new()
	regex.compile("%s\\s+(\\d+)" % word)
	var result := regex.search(text)
	if result:
		return int(result.get_string(1))
	regex.compile("%s\\s+[^0-9]*(\\d+)" % word)
	result = regex.search(text)
	return int(result.get_string(1)) if result else 0


func _first_damage_value(text: String) -> int:
	var regex := RegEx.new()
	regex.compile("(?:deal\\s+)?(\\d+)\\s+damage|damage\\s+[^0-9]*(\\d+)")
	var result := regex.search(text)
	if not result:
		return 0
	return int(result.get_string(1) if result.get_string(1) != "" else result.get_string(2))


func _build_faction_card_index() -> Dictionary:
	var result: Dictionary = {}
	for faction in factions.values():
		var name: String = faction.get("name", "")
		if name == "":
			continue
		for card_id in faction.get("card_ids", []):
			if str(card_id) == "":
				continue
			if not result.has(card_id):
				result[card_id] = []
			result[card_id].append(name)
	return result


func _normalize_card_type(raw_type, entry: Dictionary) -> String:
	var t: String = str(raw_type).strip_edges()
	match t.to_lower():
		"unit":
			return "Unit"
		"spell":
			return "Spell"
		"artifact":
			return "Artifact"
		"hero":
			return "Hero"
		_:
			pass
	if entry.get("power") != null:
		return "Unit"
	if bool(entry.get("has_ability", false)) or str(entry.get("ability_text", "")).strip_edges() != "":
		return "Spell"
	if str(entry.get("id", "")).strip_edges() != "" or str(entry.get("name", "")).strip_edges() != "":
		return "Spell"
	return "Unknown"


func _normalize_rarity(raw_rarity, entry: Dictionary) -> String:
	var rarity: String = str(raw_rarity).strip_edges()
	match rarity.to_lower():
		"common":
			return "Common"
		"rare":
			return "Rare"
		"epic":
			return "Epic"
		"legendary":
			return "Legendary"
		"hero":
			return "Hero"
		_:
			pass
	if entry.get("type", "") == "Hero":
		return "Hero"
	if entry.get("has_ability", false):
		return "Common"
	return "Common"


func _normalize_factions(card_id: String, raw_factions: Array, faction_card_index: Dictionary, entry: Dictionary) -> Array:
	var result: Array = []
	for faction in raw_factions:
		var name: String = str(faction).strip_edges()
		if name != "" and not (name in result):
			result.append(name)
	for faction in faction_card_index.get(card_id, []):
		if not (faction in result):
			result.append(faction)
	if result.is_empty() and entry.get("type", "") != "Hero":
		result.append("Neutral")
	return result


func _load_keywords() -> void:
	var kw_array: Array = _load_json_array("keywords.json")
	for entry in kw_array:
		keywords[entry.get("id", "")] = entry


func _load_statuses() -> void:
	var st_array: Array = _load_json_array("statuses.json")
	for entry in st_array:
		statuses[entry.get("id", "")] = entry


func _load_categories() -> void:
	var cat_array: Array = _load_json_array("categories.json")
	for entry in cat_array:
		categories[entry.get("id", "")] = entry


func _load_factions() -> void:
	var fac_array: Array = _load_json_array("factions.json")
	for entry in fac_array:
		factions[entry.get("id", "")] = entry
